"""initial tables

Revision ID: aece6c44a9ae
Revises: a27f7642684c
Create Date: 2023-07-02 10:21:15.410860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aece6c44a9ae'
down_revision = 'a27f7642684c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
