"""add tables

Revision ID: d38dac204657
Revises: ae06b9c34279
Create Date: 2023-07-02 09:08:09.209259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38dac204657'
down_revision = 'ae06b9c34279'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('payment_method', sa.String(), nullable=True))
    op.drop_column('invoice', 'payment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('payment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('invoice', 'payment_method')
    # ### end Alembic commands ###
