"""add tables

Revision ID: eb3cd3f712a1
Revises: d38dac204657
Create Date: 2023-07-02 09:21:24.908253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3cd3f712a1'
down_revision = 'd38dac204657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
