"""initial tables

Revision ID: f28cd5d167f1
Revises: 931e97095f3b
Create Date: 2023-07-02 19:14:11.601442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28cd5d167f1'
down_revision = '931e97095f3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
